Repository bayesflow-org/bayesflow, pull requests merged in 2024-11, with the labels that each got.

#240 Fix inference conditions broadcasting for sampling with summary networks
  bayesflow/approximators/continuous_approximator.py
  examples/Linear_Regression.ipynb
Labels: bug

#239 Allow `batch_size` instead of just `batch_shape`
  bayesflow/distributions/diagonal_normal.py
  bayesflow/distributions/diagonal_student_t.py
  bayesflow/distributions/mixture_distribution.py
  bayesflow/networks/inference_network.py
  bayesflow/simulators/hierarchical_simulator.py
  bayesflow/simulators/lambda_simulator.py
  bayesflow/simulators/model_comparison_simulator.py
  bayesflow/simulators/sequential_simulator.py
  bayesflow/simulators/simulator.py
  bayesflow/utils/decorators.py
Labels: feature, refactoring

#242 Fix LSTNet and DeepSet
  .github/workflows/tests.yaml
  bayesflow/networks/deep_set/deep_set.py
  bayesflow/networks/deep_set/equivariant_module.py
  bayesflow/networks/deep_set/invariant_module.py
  bayesflow/networks/lstnet/lstnet.py
  bayesflow/networks/lstnet/skip_recurrent.py
  bayesflow/networks/mlp/mlp.py
  tests/test_networks/conftest.py
  tests/test_networks/test_inference_networks.py
  tests/test_networks/test_summary_networks.py
  tox.ini
Labels: bug

#235 Diagnostics module
  README.md
  bayesflow/diagnostics/__init__.py
  bayesflow/diagnostics/plot_calibration_curves.py
  bayesflow/diagnostics/plot_confusion_matrix.py
  bayesflow/diagnostics/plot_losses.py
  bayesflow/diagnostics/plot_mmd_hypothesis_test.py
  bayesflow/diagnostics/plot_posterior_2d.py
  bayesflow/diagnostics/plot_prior_2d.py
  bayesflow/diagnostics/plot_recovery.py
  bayesflow/diagnostics/plot_samples_2d.py
  bayesflow/diagnostics/plot_sbc_ecdf.py
  bayesflow/diagnostics/plot_sbc_histograms.py
  bayesflow/diagnostics/plot_z_score_contraction.py
  bayesflow/utils/__init__.py
  bayesflow/utils/callbacks.py
  bayesflow/utils/comp_utils.py
  bayesflow/utils/dict_utils.py
  bayesflow/utils/exceptions/__init__.py
  bayesflow/utils/exceptions/shape_error.py
  bayesflow/utils/plot_utils.py
  bayesflow/utils/validators.py
  examples/Linear_Regression.ipynb
  examples/Quickstart_Amortized_Posterior_Estimation.ipynb
  examples/SIR_PosteriorEstimation.ipynb
  examples/TwoMoons_StarterNotebook.ipynb
  examples/mm_gsn.stan
  tests/test_diagnostics/__init__.py
  tests/test_diagnostics/conftest.py
  tests/test_diagnostics/test_diagnostics.py
Labels: duplicate, feature, refactoring, v2
