Repository bayesflow-org/bayesflow, pull requests merged in 2025-06, with the labels that each got.

#485 Correctly track train / validation losses
  bayesflow/approximators/approximator.py
  bayesflow/approximators/backend_approximators/jax_approximator.py
  bayesflow/approximators/backend_approximators/numpy_approximator.py
  bayesflow/approximators/backend_approximators/tensorflow_approximator.py
  bayesflow/approximators/backend_approximators/torch_approximator.py
  bayesflow/approximators/continuous_approximator.py
  bayesflow/approximators/model_comparison_approximator.py
Labels: fix

#505 Better pairplots
  bayesflow/diagnostics/plots/pairs_posterior.py
  bayesflow/diagnostics/plots/pairs_samples.py
  bayesflow/utils/plot_utils.py
Labels: feature, refactoring, fix

#511 Add utility function for batched simulations
  bayesflow/simulators/simulator.py
  tests/test_simulators/test_simulators.py
Labels: feature
