Repository bayesflow-org/bayesflow, pull requests merged in 2025-02, with the labels that each got.

#300 Improved Integrators
  bayesflow/__init__.py
  bayesflow/networks/flow_matching/flow_matching.py
  bayesflow/networks/flow_matching/integrators/__init__.py
  bayesflow/networks/flow_matching/integrators/euler.py
  bayesflow/networks/flow_matching/integrators/integrator.py
  bayesflow/networks/flow_matching/integrators/runge_kutta.py
  bayesflow/networks/flow_matching/integrators/runge_kutta_4.py
  bayesflow/utils/__init__.py
  bayesflow/utils/integrate.py
  bayesflow/utils/jacobian/jacobian_trace.py
  tests/conftest.py
  tests/test_networks/test_inference_networks.py
Labels: feature

#305 fix: FM, base_distribution.sample has no argument 'seed'
  bayesflow/networks/flow_matching/flow_matching.py
Labels: bug

#335 Add initial tests for diagnostic metrics
  bayesflow/utils/dict_utils.py
  tests/conftest.py
  tests/test_diagnostics/conftest.py
  tests/test_diagnostics/test_diagnostics.py
  tests/test_diagnostics/test_diagnostics_metrics.py
  tests/test_diagnostics/test_diagnostics_plots.py
Labels: draft

#338 Allow inclusive bounds in `Adapter.constrain()`
  bayesflow/adapters/adapter.py
  bayesflow/adapters/transforms/constrain.py
  tests/test_adapters/test_adapters.py
Labels: sugar

#202 add tests for summary networks [WIP]
  bayesflow/networks/transformers/fusion_transformer.py
  bayesflow/networks/transformers/set_transformer.py
  bayesflow/networks/transformers/time_series_transformer.py
  tests/conftest.py
  tests/test_networks/conftest.py
  tests/test_networks/test_summary_networks.py
  tests/test_two_moons/conftest.py
Labels: unit tests, good first issue
