Repository bayesflow-org/bayesflow, pull requests merged in 2025-04, with the labels that each got.

#381 Populate API Reference landing page
  bayesflow/adapters/__init__.py
  bayesflow/approximators/__init__.py
  bayesflow/datasets/__init__.py
  bayesflow/diagnostics/__init__.py
  bayesflow/distributions/__init__.py
  bayesflow/experimental/__init__.py
  bayesflow/metrics/__init__.py
  bayesflow/networks/__init__.py
  bayesflow/simulators/__init__.py
  bayesflow/types/__init__.py
  bayesflow/utils/__init__.py
  bayesflow/workflows/__init__.py
Labels: documentation

#394 Adapter scale and shift
  bayesflow/adapters/adapter.py
  bayesflow/adapters/transforms/__init__.py
  bayesflow/adapters/transforms/scale.py
  bayesflow/adapters/transforms/shift.py
  tests/test_adapters/conftest.py
  tests/test_adapters/test_adapters.py
Labels: feature, user interface, good first issue, sugar

#396 Force contiguous searchsorted
  bayesflow/__init__.py
  bayesflow/utils/tensor_utils.py
Labels: fix

#397 Allow positional include transforms
  bayesflow/adapters/adapter.py
  bayesflow/adapters/transforms/filter_transform.py
  bayesflow/utils/empty.py
Labels: feature, user interface, sugar

#398 Enable Mamba as Summary Nets
  bayesflow/wrappers/__init__.py
  bayesflow/wrappers/mamba/__init__.py
  bayesflow/wrappers/mamba/mamba.py
  bayesflow/wrappers/mamba/mamba_block.py
  tests/test_wrappers/__init__.py
  tests/test_wrappers/conftest.py
  tests/test_wrappers/test_mamba.py
Labels: feature

#414 Fix gaussian linear benchmark, expose benchmark simulators.
  bayesflow/simulators/__init__.py
  bayesflow/simulators/benchmark_simulators/__init__.py
  bayesflow/simulators/benchmark_simulators/gaussian_linear.py
  bayesflow/simulators/benchmark_simulators/gaussian_linear_uniform.py
  tests/test_simulators/conftest.py
  tests/test_simulators/test_simulators.py
Labels: fix

#416 Add Pandas `to_dict` adapter transform
  bayesflow/adapters/adapter.py
  bayesflow/adapters/transforms/__init__.py
  bayesflow/adapters/transforms/split.py
  bayesflow/adapters/transforms/to_array.py
  bayesflow/adapters/transforms/to_dict.py
  tests/test_adapters/test_adapters.py
Labels: feature, user interface

#435 Drastically Improve Speed of Import
  bayesflow/utils/_docs/_populate_all.py
  bayesflow/utils/serialization.py
  tests/test_utils/test_dispatch.py
Labels: efficiency

#425 Adapt inference network tests to support non-invertible architectures
  tests/test_networks/conftest.py
  tests/test_networks/test_inference_networks.py
Labels: unit tests

#434 Enable use of summary networks with functional API again
  bayesflow/links/ordered.py
  bayesflow/networks/summary_network.py
  bayesflow/networks/transformers/mab.py
  bayesflow/networks/transformers/pma.py
  bayesflow/networks/transformers/sab.py
  bayesflow/utils/decorators.py
  tests/test_networks/test_summary_networks.py
Labels: fix

#437 More tests
  bayesflow/networks/coupling_flow/coupling_flow.py
  tests/test_networks/test_coupling_flow/test_permutations.py
  tests/test_networks/test_embeddings.py
Labels: unit tests

#446 Fix Optimal Transport for Compiled Contexts
  bayesflow/utils/optimal_transport/log_sinkhorn.py
  bayesflow/utils/optimal_transport/sinkhorn.py
  tests/test_examples/test_examples.py
Labels: fix

#427 Add advice regarding moving from v1 to v2 to README.
  README.md
  docsrc/source/index.md
Labels: documentation
